services:
  ryu-mitm:
    build: .
    container_name: ryu-mitm
    network_mode: "host"
    volumes:
      - .:/app
    restart: unless-stopped
    privileged: true
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "6633"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: ryu-manager my_controller.py
